### ISSUE TITLE
Detect better

### ISSUE THREAD

**Issue by erisu** [NiklasMerz/release-notify#4]
Give me my release!
ASAP!!
NOW!
OMG PLEASE!!!
I AM BEGGING YOU!!!
RELEASE!!!

**Comment by timbru31** [comment]
And when do you enable for Apache

**Comment by NiklasMerz** [comment]
Maybe we should adjust this:https://github.com/NiklasMerz/release-notify/blob/7d9904942416848dc74a5ec1e1bb7459a3726a57/src/main.js#L4-L8

And check for stuff in all CAPS :-)

**Comment by NiklasMerz** [comment]
> And when do you enable for Apache 

Do we have consensus that this is a good idea? Should we test it in one repo first?

**Comment by erisu** [comment]
Please put this into Camera first at least :D

**Comment by erisu** [comment]
I even just started the thread for next release and they still asking :(

**Comment by NiklasMerz** [comment]
Then let's use Camera as a proving ground.

**Comment by erisu** [comment]
consensus wise, most people didn't even leave a comment. I can leave a comment with a +1 to try and reactive the vote/discussion.. I am for it if we can improve

**Comment by erisu** [comment]
I always been trying to improve the issue tracker/management but fail to get consensus or votes..

**Comment by NiklasMerz** [comment]
Let's test it out and see how it works. Then we can roll it out to other repos after collecting consensus. Another improvement would be to add a comment about this behavior to contributin:

PR for camera: https://github.com/apache/cordova-plugin-camera/pull/654

**Comment by NiklasMerz** [comment]
I invited you to this repo if you want to make any changes. Hopefully I find some time tonight to improve this a bit.

**Comment by NiklasMerz** [comment]
I just did some changes and added some random penalties
